name: project-ci
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      
      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run lint 

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      
      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test 
  
  build:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      script-file: ${{ steps.publish_step.outputs.script-file }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
    
      - name: Install Dependencies
        run: npm ci 

      - name: Build
        run: npm run build

      - name: Publish JS filename
        id: publish_step
        run: find dist/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'

      - uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: './dist'

  display-output:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Display Output JS Filename
        run: echo "${{ needs.build.outputs.script-file }}"
